services:
  app:
    image: garonix/sslinker
    container_name: sslinker
    ports:
      - "8089:8000"
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/certs
      - ./nginx:/etc/nginx/conf.d
      - ./config:/app/backend/config
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
